#!/bin/sh
#

#before running script make sure you've typed:
# freesurfer_5.3.0
# mne_setup_2.7.3_64bit
# setenv SUBJECTS_DIR /imaging/rf02/TypLexMEG/


################
# PARAMETERS:

# Input/Output file path:

#path='/megdata/cbu/PATH/TO/YOUR/DATA'
#path='/group/erp/data/olaf.hauk/Others/Miozzo/data'
#MRIpath='/group/erp/data/olaf.hauk/Others/Miozzo/MRIs'

outpath='/imaging/rf02/Semnet/stc/mov/permutation/evoked/pnt1_30' #'/imaging/rf02/TypLexMEG/icaanalysis_results/jpg/permutation/connectivity/WB_hubs/to_use' #connectivity/WB_spokes/spectral'  # output directory for images
#inpath='/imaging/olaf/MEG/GoNoGo/STC/GM'
inpath='/imaging/rf02/Semnet/stc/permutation/evoked/pnt1_30' #'/imaging/rf02/TypLexMEG/icaanalysis_results/stc/UVttest/connectivity/WB_hubs/newp' #connectivity/WB_spokes/spectral/older'


# /imaging/olaf/MEG/GoNoGo/STC/GM/GM_lex_wdspds_n18.stc
########################

### All Conditions
conds=(\


#'Permutation_stepwise_clusterp025_p05_17subj_typlex_icaclean_subtract_SourcePower_induced_ratio_equalized_50_550_100ms_maxstep5theta' \
#'Permutation_stepwise_clusterp025_p05_17subj_typlex_icaclean_subtract_SourcePower_induced_ratio_equalized_50_550_100ms_maxstep5alpha' \
#'ClusterPermutation_abs_stepwise_firstmorphed_clusterp05_p00888048780488_17subj_typlex_icaclean_WordPW_50_550_100ms_tail0_maxstep5' \
#'UVttest_firstMorphed_typlex_icaclean_Subtract_Source_Evoked_meanresampled_50_550_100ms_0overlap' \
#'UVttest_firstMorphed_typlex_icaclean_equalized_Subtract_Multitaper_MaxLabel_Coherence_Alpha_150_450_200ms_lh.ATL_lat' \
#'UVttest_firstMorphed_typlex_icaclean_equalized_Subtract_Multitaper_MaxLabel_Coherence_Alpha_150_450_200ms_rh.ATL_lat' \
#'UVttest_firstMorphed_typlex_icaclean_equalized_Subtract_Multitaper_MaxLabel_Coherence_Gamma_150_450_200ms_lh.ATL_lat' \
#'UVttest_firstMorphed_typlex_icaclean_equalized_Subtract_Multitaper_MaxLabel_Coherence_Gamma_150_450_200ms_rh.ATL_lat' \
#'UVttest_firstMorphed_typlex_icaclean_equalized_Subtract_Multitaper_MaxLabel_Coherence_Theta_150_450_200ms_lh.ATL_lat' \
#'UVttest_firstMorphed_typlex_icaclean_equalized_Subtract_Multitaper_MaxLabel_Coherence_Theta_150_450_200ms_rh.ATL_lat' \
#'UVttest_firstMorphed_typlex_icaclean_equalized_Subtract_Multitaper_MaxLabel_Coherence_Beta_150_450_200ms_lh.ATL_lat' \
#'UVttest_firstMorphed_typlex_icaclean_equalized_Subtract_Multitaper_MaxLabel_Coherence_Beta_150_450_200ms_rh.ATL_lat' \
#'UVttest_firstMorphed_typlex_icaclean_equalized_Subtract_Multitaper_MaxLabel_PPC_Alpha_150_450_200ms_lh.ATL_lat' \
#'UVttest_firstMorphed_typlex_icaclean_equalized_Subtract_Multitaper_MaxLabel_PPC_Alpha_150_450_200ms_rh.ATL_lat' \
#'UVttest_firstMorphed_typlex_icaclean_equalized_Subtract_Multitaper_MaxLabel_PPC_Gamma_150_450_200ms_lh.ATL_lat' \
#'UVttest_firstMorphed_typlex_icaclean_equalized_Subtract_Multitaper_MaxLabel_PPC_Gamma_150_450_200ms_rh.ATL_lat' \
#'UVttest_firstMorphed_typlex_icaclean_equalized_Subtract_Multitaper_MaxLabel_PPC_Theta_150_450_200ms_lh.ATL_lat' \
#'UVttest_firstMorphed_typlex_icaclean_equalized_Subtract_Multitaper_MaxLabel_PPC_Theta_150_450_200ms_rh.ATL_lat' \
#'UVttest_firstMorphed_typlex_icaclean_equalized_Subtract_Multitaper_MaxLabel_PPC_Beta_150_450_200ms_lh.ATL_lat' \
#'UVttest_firstMorphed_typlex_icaclean_equalized_Subtract_Multitaper_MaxLabel_PPC_Beta_150_450_200ms_rh.ATL_lat' \

#'UVttest_firstMorphed_typlex_icaclean_equalized_Subtract_Multitaper_MaxLabel_Coherence_Alpha_150_450_200ms_lh.posterior_fusif' \
#'UVttest_firstMorphed_typlex_icaclean_equalized_Subtract_Multitaper_MaxLabel_Coherence_Alpha_150_450_200ms_rh.posterior_fusif' \
#'UVttest_firstMorphed_typlex_icaclean_equalized_Subtract_Multitaper_MaxLabel_Coherence_Gamma_150_450_200ms_lh.posterior_fusif' \
#'UVttest_firstMorphed_typlex_icaclean_equalized_Subtract_Multitaper_MaxLabel_Coherence_Gamma_150_450_200ms_rh.posterior_fusif' \
#'UVttest_firstMorphed_typlex_icaclean_equalized_Subtract_Multitaper_MaxLabel_Coherence_Theta_150_450_200ms_lh.posterior_fusif' \
#'UVttest_firstMorphed_typlex_icaclean_equalized_Subtract_Multitaper_MaxLabel_Coherence_Theta_150_450_200ms_rh.posterior_fusif' \
#'UVttest_firstMorphed_typlex_icaclean_equalized_Subtract_Multitaper_MaxLabel_Coherence_Beta_150_450_200ms_lh.posterior_fusif' \
#'UVttest_firstMorphed_typlex_icaclean_equalized_Subtract_Multitaper_MaxLabel_Coherence_Beta_150_450_200ms_rh.posterior_fusif' \
#'UVttest_firstMorphed_typlex_icaclean_equalized_Subtract_Multitaper_MaxLabel_PPC_Alpha_150_450_200ms_lh.posterior_fusif' \
#'UVttest_firstMorphed_typlex_icaclean_equalized_Subtract_Multitaper_MaxLabel_PPC_Alpha_150_450_200ms_rh.posterior_fusif' \
#'UVttest_firstMorphed_typlex_icaclean_equalized_Subtract_Multitaper_MaxLabel_PPC_Gamma_150_450_200ms_lh.posterior_fusif' \
#'UVttest_firstMorphed_typlex_icaclean_equalized_Subtract_Multitaper_MaxLabel_PPC_Gamma_150_450_200ms_rh.posterior_fusif' \
#'UVttest_firstMorphed_typlex_icaclean_equalized_Subtract_Multitaper_MaxLabel_PPC_Theta_150_450_200ms_lh.posterior_fusif' \
#'UVttest_firstMorphed_typlex_icaclean_equalized_Subtract_Multitaper_MaxLabel_PPC_Theta_150_450_200ms_rh.posterior_fusif' \
#'UVttest_firstMorphed_typlex_icaclean_equalized_Subtract_Multitaper_MaxLabel_PPC_Beta_150_450_200ms_lh.posterior_fusif' \
#'UVttest_firstMorphed_typlex_icaclean_equalized_Subtract_Multitaper_MaxLabel_PPC_Beta_150_450_200ms_rh.posterior_fusif' \

#'UVttest_firstMorphed_typlex_icaclean_equalized_Subtract_Multitaper_MaxLabel_Coherence_Alpha_150_450_200ms_lh.lateraloccipi' \
#'UVttest_firstMorphed_typlex_icaclean_equalized_Subtract_Multitaper_MaxLabel_Coherence_Alpha_150_450_200ms_rh.lateraloccipi' \
#'UVttest_firstMorphed_typlex_icaclean_equalized_Subtract_Multitaper_MaxLabel_Coherence_Gamma_150_450_200ms_lh.lateraloccipi' \
#'UVttest_firstMorphed_typlex_icaclean_equalized_Subtract_Multitaper_MaxLabel_Coherence_Gamma_150_450_200ms_rh.lateraloccipi' \
#'UVttest_firstMorphed_typlex_icaclean_equalized_Subtract_Multitaper_MaxLabel_Coherence_Theta_150_450_200ms_lh.lateraloccipi' \
#'UVttest_firstMorphed_typlex_icaclean_equalized_Subtract_Multitaper_MaxLabel_Coherence_Theta_150_450_200ms_rh.lateraloccipi' \
#'UVttest_firstMorphed_typlex_icaclean_equalized_Subtract_Multitaper_MaxLabel_Coherence_Beta_150_450_200ms_lh.lateraloccipi' \
#'UVttest_firstMorphed_typlex_icaclean_equalized_Subtract_Multitaper_MaxLabel_Coherence_Beta_150_450_200ms_rh.lateraloccipi' \
#'UVttest_firstMorphed_typlex_icaclean_equalized_Subtract_Multitaper_MaxLabel_PPC_Alpha_150_450_200ms_lh.lateraloccipi' \
#'UVttest_firstMorphed_typlex_icaclean_equalized_Subtract_Multitaper_MaxLabel_PPC_Alpha_150_450_200ms_rh.lateraloccipi' \
#'UVttest_firstMorphed_typlex_icaclean_equalized_Subtract_Multitaper_MaxLabel_PPC_Gamma_150_450_200ms_lh.lateraloccipi' \
#'UVttest_firstMorphed_typlex_icaclean_equalized_Subtract_Multitaper_MaxLabel_PPC_Gamma_150_450_200ms_rh.lateraloccipi' \
#'UVttest_firstMorphed_typlex_icaclean_equalized_Subtract_Multitaper_MaxLabel_PPC_Theta_150_450_200ms_lh.lateraloccipi' \
#'UVttest_firstMorphed_typlex_icaclean_equalized_Subtract_Multitaper_MaxLabel_PPC_Theta_150_450_200ms_rh.lateraloccipi' \
#'UVttest_firstMorphed_typlex_icaclean_equalized_Subtract_Multitaper_MaxLabel_PPC_Beta_150_450_200ms_lh.lateraloccipi' \
#'UVttest_firstMorphed_typlex_icaclean_equalized_Subtract_Multitaper_MaxLabel_PPC_Beta_150_450_200ms_rh.lateraloccipi' \

#'UVttest_firstMorphed_typlex_icaclean_equalized_Subtract_Multitaper_MaxLabel_Coherence_Alpha_150_450_200ms_lh.precent' \
#'UVttest_firstMorphed_typlex_icaclean_equalized_Subtract_Multitaper_MaxLabel_Coherence_Alpha_150_450_200ms_rh.precent' \
#'UVttest_firstMorphed_typlex_icaclean_equalized_Subtract_Multitaper_MaxLabel_Coherence_Gamma_150_450_200ms_lh.precent' \
#'UVttest_firstMorphed_typlex_icaclean_equalized_Subtract_Multitaper_MaxLabel_Coherence_Gamma_150_450_200ms_rh.precent' \
#'UVttest_firstMorphed_typlex_icaclean_equalized_Subtract_Multitaper_MaxLabel_Coherence_Theta_150_450_200ms_lh.precent' \
#'UVttest_firstMorphed_typlex_icaclean_equalized_Subtract_Multitaper_MaxLabel_Coherence_Theta_150_450_200ms_rh.precent' \
#'UVttest_firstMorphed_typlex_icaclean_equalized_Subtract_Multitaper_MaxLabel_Coherence_Beta_150_450_200ms_lh.precent' \
#'UVttest_firstMorphed_typlex_icaclean_equalized_Subtract_Multitaper_MaxLabel_Coherence_Beta_150_450_200ms_rh.precent' \
#'UVttest_firstMorphed_typlex_icaclean_equalized_Subtract_Multitaper_MaxLabel_PPC_Alpha_150_450_200ms_lh.precent' \
#'UVttest_firstMorphed_typlex_icaclean_equalized_Subtract_Multitaper_MaxLabel_PPC_Alpha_150_450_200ms_rh.precent' \
#'UVttest_firstMorphed_typlex_icaclean_equalized_Subtract_Multitaper_MaxLabel_PPC_Gamma_150_450_200ms_lh.precent' \
#'UVttest_firstMorphed_typlex_icaclean_equalized_Subtract_Multitaper_MaxLabel_PPC_Gamma_150_450_200ms_rh.precent' \
#'UVttest_firstMorphed_typlex_icaclean_equalized_Subtract_Multitaper_MaxLabel_PPC_Theta_150_450_200ms_lh.precent' \
#'UVttest_firstMorphed_typlex_icaclean_equalized_Subtract_Multitaper_MaxLabel_PPC_Theta_150_450_200ms_rh.precent' \
#'UVttest_firstMorphed_typlex_icaclean_equalized_Subtract_Multitaper_MaxLabel_PPC_Beta_150_450_200ms_lh.precent' \
#'UVttest_firstMorphed_typlex_icaclean_equalized_Subtract_Multitaper_MaxLabel_PPC_Beta_150_450_200ms_rh.precent' \

#'ClusPermutation_stepwise_firstMorphed_typlex_icaclean_equalized_Subtract_Multitaper_MaxLabel_Coherence_Beta_150_450_200ms_maxstep1_025_05_rh.precent' \
#'ClusPermutation_stepwise_firstMorphed_typlex_icaclean_equalized_Subtract_Multitaper_MaxLabel_Coherence_Beta_150_450_200ms_maxstep1_025_05_lh.lateraloccipi' \
#'ClusPermutation_stepwise_firstMorphed_typlex_icaclean_equalized_Subtract_Multitaper_MaxLabel_Coherence_Gamma_150_450_200ms_maxstep1_01_05_lh.precent' \
#'ClusPermutation_stepwise_firstMorphed_typlex_icaclean_equalized_Subtract_Multitaper_MaxLabel_PPC_Alpha_150_450_200ms_maxstep1_005_05_lh.lateraloccipi' \
#'ClusPermutation_stepwise_firstMorphed_typlex_icaclean_equalized_Subtract_Multitaper_MaxLabel_PPC_Beta_150_450_200ms_maxstep1_05_05_lh.lateraloccipi' \
#'ClusPermutation_stepwise_firstMorphed_typlex_icaclean_equalized_Subtract_Multitaper_MaxLabel_PPC_Gamma_150_450_200ms_maxstep1_05_05_rh.precent' \
#'ClusPermutation_stepwise_firstMorphed_typlex_icaclean_equalized_Subtract_Multitaper_MaxLabel_PPC_Gamma_150_450_200ms_maxstep1_025_05_lh.ATL_lat' \
#'UVttest_mineMorphed_SemLoc_icaclean_Subtract_Power_ratio_equalized_meanresampled_50_550_100ms_0overlap_theta' \
#'UVttest_mineMorphed_SemLoc_icaclean_Subtract_Power_ratio_equalized_meanresampled_50_550_100ms_0overlap_beta' \
#'UVttest_mineMorphed_SemLoc_icaclean_Subtract_Power_ratio_equalized_meanresampled_50_550_100ms_0overlap_alpha' \
#'UVttest_mineMorphed_SemLoc_icaclean_Subtract_Power_ratio_equalized_meanresampled_50_550_100ms_0overlap_gamma' \

#'UVttest_mineMorphed_typlex_icaclean_Subtract_Power_ratio_equalized_meanresampled_50_550_100ms_0overlap_alpha' \
#'UVttest_mineMorphed_typlex_icaclean_Subtract_Power_ratio_equalized_meanresampled_50_550_100ms_0overlap_gamma' \
#'UVttest_mineMorphed_typlex_icaclean_Subtract_Power_ratio_equalized_meanresampled_50_550_100ms_0overlap_beta' \
#'UVttest_mineMorphed_typlex_icaclean_Subtract_Power_ratio_equalized_meanresampled_50_550_100ms_0overlap_theta' \

#'Permutation_stepwise_clusterp05_p05_17subj_typlex_icaclean_subtract_Power_mine_ratio_equalized_50_550_100ms_maxstep5theta' \
#'Permutation_stepwise_clusterp05_p05_17subj_typlex_icaclean_subtract_Power_mine_ratio_equalized_50_550_100ms_maxstep5beta' \
#'Permutation_stepwise_clusterp05_p05_17subj_typlex_icaclean_subtract_Power_mine_ratio_equalized_50_550_100ms_maxstep5alpha' \

#'Permutation_stepwise_clusterp05_p05_17subj_SemLoc_icaclean_Subtract_Power_mine_ratio_equalized_50_550_100ms_sx_maxstep5theta' \
#'Permutation_stepwise_clusterp05_p05_17subj_SemLoc_icaclean_Subtract_rPLV_mine_normori_equalized_50_550_100ms_sx_maxstep5theta' \
#'Permutation_stepwise_clusterp01_p05_17subj_SemLoc_icaclean_Subtract_rPLV_mine_normori_equalized_50_550_100ms_sx_maxstep5theta' \
#'Permutation_stepwise_clusterp05_p05_17subj_SemLoc_icaclean_Subtract_Power_mine_logratio_normori_equalized_50_550_100ms_sx_maxstep5theta' \
#'Permutation_stepwise_clusterp01_p05_17subj_SemLoc_icaclean_Subtract_Power_mine_ratio_normori_equalized_50_550_100ms_sx_maxstep5theta' \
#'Permutation_stepwise_clusterp01_p05_17subj_typlex_icaclean_Subtract_rPLV_ratio_mine_normori_equalized_50_550_100ms_sx_maxstep5beta' \
#'Permutation_stepwise_clusterp01_p05_17subj_typlex_icaclean_Subtract_Power_ratio_mine_normori_equalized_50_550_100ms_sx_maxstep5theta' \
#'Permutation_stepwise_clusterp01_p05_17subj_typlex_icaclean_Subtract_Power_ratio_mine_normori_equalized_50_550_100ms_sx_maxstep5alpha-rh' \
#'ClusPer_stepwise_Morphed_SemLoc_ica_equalized_Subtract_Mlttap_bestV_ctf_Coherence_Theta_150_450_200ms_maxstep1_005_05_posterior_inferiorfrontal' \
#'ClusPer_stepwise_Morphed_SemLoc_ica_equalized_Subtract_Mlttap_bestV_ctf_PPC_Alpha_150_450_200ms_maxstep1_005_05_ATL_latmed' \
#'ClusPer_stepwise_Morphed_SemLoc_ica_equalized_Subtract_Mlttap_bestV_ctf_PPC_Gamma_150_450_200ms_maxstep1_001_05_middle_temporal' \

#'ClusPermutation_stepwise_Morphed_typlex_ica_equalized_sub_Mlttap_bestV_ctf_Coherence_Alpha_150_450_200ms/imaging/rf02/TypLexMEG/icaanalysis_results/stc/UVttest/connectivity/WB_hubs/newp_sx_ms1_003_05_ATL_latmed' \
#'ClusPermutation_stepwise_Morphed_typlex_ica_equalized_sub_Mlttap_bestV_ctf_Coherence_Theta_150_450_200ms_sx_ms1_004_05_posterior_inferiorfrontal' \
#'ClusPermutation_stepwise_Morphed_typlex_ica_equalized_sub_Mlttap_bestV_ctf_Coherence_Theta_150_450_200ms_sx_ms1_005_05_middle_temporal' \
#'ClusPermutation_stepwise_Morphed_typlex_ica_equalized_sub_Mlttap_bestV_ctf_PPC_Gamma_150_450_200ms_sx_ms1_004_05_middle_temporal' \
#'ClusPermutation_stepwise_Morphed_typlex_ica_equalized_sub_Mlttap_bestV_ctf_PPC_Theta_150_450_200ms_sx_ms1_003_05_supramarginal' \

#'UVttest_Morphed_typlex_ica_equalized_subtract_Mlttap_bestV_ctf_Coherence_Theta_150_450_200ms_lhmiddle_temporal' \
#'UVttest_Morphed_typlex_ica_equalized_subtract_Mlttap_bestV_ctf_Coherence_Alpha_150_450_200ms_lhmiddle_temporal' \
#'UVttest_Morphed_typlex_ica_equalized_subtract_Mlttap_bestV_ctf_Coherence_Beta_150_450_200ms_lhmiddle_temporal' \
#'UVttest_Morphed_typlex_ica_equalized_subtract_Mlttap_bestV_ctf_Coherence_Gamma_150_450_200ms_lhmiddle_temporal' \
#'UVttest_Morphed_typlex_ica_equalized_subtract_Mlttap_bestV_ctf_PPC_Theta_150_450_200ms_lhmiddle_temporal' \
#'UVttest_Morphed_typlex_ica_equalized_subtract_Mlttap_bestV_ctf_PPC_Alpha_150_450_200ms_lhmiddle_temporal' \
#'UVttest_Morphed_typlex_ica_equalized_subtract_Mlttap_bestV_ctf_PPC_Beta_150_450_200ms_lhmiddle_temporal' \
#'UVttest_Morphed_typlex_ica_equalized_subtract_Mlttap_bestV_ctf_PPC_Gamma_150_450_200ms_lhmiddle_temporal' \

#'UVttest_Morphed_typlex_ica_equalized_subtract_Mlttap_bestV_ctf_Coherence_Theta_150_450_200ms_lhposterior_inferiorfrontal' \
#'UVttest_Morphed_typlex_ica_equalized_subtract_Mlttap_bestV_ctf_Coherence_Alpha_150_450_200ms_lhposterior_inferiorfrontal' \
#'UVttest_Morphed_typlex_ica_equalized_subtract_Mlttap_bestV_ctf_Coherence_Beta_150_450_200ms_lhposterior_inferiorfrontal' \
#'UVttest_Morphed_typlex_ica_equalized_subtract_Mlttap_bestV_ctf_Coherence_Gamma_150_450_200ms_lhposterior_inferiorfrontal' \
#'UVttest_Morphed_typlex_ica_equalized_subtract_Mlttap_bestV_ctf_PPC_Theta_150_450_200ms_lhposterior_inferiorfrontal' \
#'UVttest_Morphed_typlex_ica_equalized_subtract_Mlttap_bestV_ctf_PPC_Alpha_150_450_200ms_lhposterior_inferiorfrontal' \
#'UVttest_Morphed_typlex_ica_equalized_subtract_Mlttap_bestV_ctf_PPC_Beta_150_450_200ms_lhposterior_inferiorfrontal' \
#'UVttest_Morphed_typlex_ica_equalized_subtract_Mlttap_bestV_ctf_PPC_Gamma_150_450_200ms_lhposterior_inferiorfrontal' \

#'UVttest_Morphed_typlex_ica_equalized_subtract_Mlttap_bestV_ctf_Coherence_Theta_150_450_200ms_lhsupramarginal' \
#'UVttest_Morphed_typlex_ica_equalized_subtract_Mlttap_bestV_ctf_Coherence_Alpha_150_450_200ms_lhsupramarginal' \
#'UVttest_Morphed_typlex_ica_equalized_subtract_Mlttap_bestV_ctf_Coherence_Beta_150_450_200ms_lhsupramarginal' \
#'UVttest_Morphed_typlex_ica_equalized_subtract_Mlttap_bestV_ctf_Coherence_Gamma_150_450_200ms_lhsupramarginal' \
#'UVttest_Morphed_typlex_ica_equalized_subtract_Mlttap_bestV_ctf_PPC_Theta_150_450_200ms_lhsupramarginal' \
#'UVttest_Morphed_typlex_ica_equalized_subtract_Mlttap_bestV_ctf_PPC_Alpha_150_450_200ms_lhsupramarginal' \
#'UVttest_Morphed_typlex_ica_equalized_subtract_Mlttap_bestV_ctf_PPC_Beta_150_450_200ms_lhsupramarginal' \
#'UVttest_Morphed_typlex_ica_equalized_subtract_Mlttap_bestV_ctf_PPC_Gamma_150_450_200ms_lhsupramarginal' \

#'UVttest_Morphed_typlex_ica_equalized_subtract_Mlttap_bestV_ctf_Coherence_Theta_150_450_200ms_lhATL_latmed' \
#'UVttest_Morphed_typlex_ica_equalized_subtract_Mlttap_bestV_ctf_Coherence_Alpha_150_450_200ms_lhATL_latmed' \
#'UVttest_Morphed_typlex_ica_equalized_subtract_Mlttap_bestV_ctf_Coherence_Beta_150_450_200ms_lhATL_latmed' \
#'UVttest_Morphed_typlex_ica_equalized_subtract_Mlttap_bestV_ctf_Coherence_Gamma_150_450_200ms_lhATL_latmed' \
#'UVttest_Morphed_typlex_ica_equalized_subtract_Mlttap_bestV_ctf_PPC_Theta_150_450_200ms_lhATL_latmed' \
#'UVttest_Morphed_typlex_ica_equalized_subtract_Mlttap_bestV_ctf_PPC_Alpha_150_450_200ms_lhATL_latmed' \
#'UVttest_Morphed_typlex_ica_equalized_subtract_Mlttap_bestV_ctf_PPC_Beta_150_450_200ms_lhATL_latmed' \
#'UVttest_Morphed_typlex_ica_equalized_subtract_Mlttap_bestV_ctf_PPC_Gamma_150_450_200ms_lhATL_latmed' \

#'UVttest_mineMorphed_SemLoc_ica_Subtract_Power_normori_ratio_equalized_50_550_100ms_0ov_200hz_theta' \
#'UVttest_mineMorphed_SemLoc_ica_Subtract_Power_normori_ratio_equalized_50_550_100ms_0ov_200hz_alpha' \
#'UVttest_mineMorphed_SemLoc_ica_Subtract_Power_normori_ratio_equalized_50_550_100ms_0ov_200hz_beta' \
#'UVttest_mineMorphed_SemLoc_ica_Subtract_Power_normori_ratio_equalized_50_550_100ms_0ov_200hz_gamma' \
#'UVttest_mineMorphed_SemLoc_ica_Subtract_rPLV_normori_equalized_50_550_100ms_0ov_200hz_theta' \
#'UVttest_mineMorphed_SemLoc_ica_Subtract_rPLV_normori_equalized_50_550_100ms_0ov_200hz_alpha' \
#'UVttest_mineMorphed_SemLoc_ica_Subtract_rPLV_normori_equalized_50_550_100ms_0ov_200hz_beta' \
#'UVttest_mineMorphed_SemLoc_ica_Subtract_rPLV_normori_equalized_50_550_100ms_0ov_200hz_gamma' \

#'UVttest_mineMorphed_typlex_ica_Subtract_Power_normori_ratio_equalized_meanresampled_50_550_100ms_0ov_200hz_theta' \
#'UVttest_mineMorphed_typlex_ica_Subtract_Power_normori_ratio_equalized_meanresampled_50_550_100ms_0ov_200hz_alpha' \
#'UVttest_mineMorphed_typlex_ica_Subtract_Power_normori_ratio_equalized_meanresampled_50_550_100ms_0ov_200hz_beta' \
#'UVttest_mineMorphed_typlex_ica_Subtract_Power_normori_ratio_equalized_meanresampled_50_550_100ms_0ov_200hz_gamma' \
#'UVttest_mineMorphed_typlex_ica_Subtract_rPLV_normori_equalized_meanresampled_50_550_100ms_0ov_200hz_theta' \
#'UVttest_mineMorphed_typlex_ica_Subtract_rPLV_normori_equalized_meanresampled_50_550_100ms_0ov_200hz_alpha' \
#'UVttest_mineMorphed_typlex_ica_Subtract_rPLV_normori_equalized_meanresampled_50_550_100ms_0ov_200hz_beta' \
#'UVttest_mineMorphed_typlex_ica_Subtract_rPLV_normori_equalized_meanresampled_50_550_100ms_0ov_200hz_gamma' \

#'Permutation_stepwise_clusterp008_p05_17subj_SemLoc_icaclean_Subtract_rPLV_mine_ratio_normori_equalized_50_550_100ms_sx_maxstep5theta' \


#'ClusPer_stepw_Morphed_TL_ica_equal_Sub_bestV_ctf_MI_Alpha_150_450_200ms_ms1_sx_005_05_lhSMG' \

#'UVttest_Morphed_SL_ica_equal_sub_MI_bestV_ctf_Alpha_150_450_200ms_lhATL' \
#'UVttest_Morphed_SL_ica_equal_sub_MI_bestV_ctf_Beta_150_450_200ms_lhATL' \
#'ClusPer_stepw_Morphed_SL_ica_equal_Sub_bestV_ctf_MI_Beta_150_450_200ms_ms1_sx_05_05_lhATL' \
#'ClusPer_stepw_Morphed_SL_ica_equal_Sub_bestV_ctf_MI_Alpha_150_450_200ms_ms1_sx_05_05_lhATL' \
#'UVttest_Morphed_SL_ica_equal_sub_MI_bestV_ctf_Theta_150_450_200ms_lhSMG' \
#'UVttest_Morphed_SL_ica_equal_sub_MI_bestV_ctf_Alpha_150_450_200ms_lhSMG' \
#'UVttest_Morphed_SL_ica_equal_sub_MI_bestV_ctf_Beta_150_450_200ms_lhSMG' \
#'UVttest_Morphed_SL_ica_equal_sub_MI_bestV_ctf_Gamma_150_450_200ms_lhSMG' \
#'UVttest_Morphed_SL_ica_equal_sub_MI_bestV_ctf_Theta_150_450_200ms_lhATL' \
#'UVttest_Morphed_SL_ica_equal_sub_MI_bestV_ctf_Alpha_150_450_200ms_lhATL' \
#'UVttest_Morphed_SL_ica_equal_sub_MI_bestV_ctf_Beta_150_450_200ms_lhATL' \
#'UVttest_Morphed_SL_ica_equal_sub_MI_bestV_ctf_Gamma_150_450_200ms_lhATL' \
#'UVttest_Morphed_SL_ica_equal_sub_MI_bestV_ctf_Theta_150_450_200ms_lhpIFG' \
#'UVttest_Morphed_SL_ica_equal_sub_MI_bestV_ctf_Alpha_150_450_200ms_lhpIFG' \
#'UVttest_Morphed_SL_ica_equal_sub_MI_bestV_ctf_Beta_150_450_200ms_lhpIFG' \
#'UVttest_Morphed_SL_ica_equal_sub_MI_bestV_ctf_Gamma_150_450_200ms_lhpIFG' \
#'UVttest_Morphed_SL_ica_equal_sub_MI_bestV_ctf_Theta_150_450_200ms_lhMTL' \
#'UVttest_Morphed_SL_ica_equal_sub_MI_bestV_ctf_Alpha_150_450_200ms_lhMTL' \
#'UVttest_Morphed_SL_ica_equal_sub_MI_bestV_ctf_Beta_150_450_200ms_lhMTL' \
#'UVttest_Morphed_SL_ica_equal_sub_MI_bestV_ctf_Gamma_150_450_200ms_lhMTL' \

### permutation
##semloc power
#'Per_sw_clusp0001_p05_SL_ica_Subtract_Power_ratio_normori_eq_50_550_100ms_sx_ms5theta' \

##typlex power
#'Per_sw_clusp05_p05_TL_ica_Subtract_Power_ico_mine_normori_eq_50_550_100ms_sx_ms5alpha' \
#'Per_sw_clusp05_p05_TL_ica_Subtract_Power_ico_mine_normori_eq_50_550_100ms_sx_ms5beta' \
#'Per_sw_clusp04_p05_TL_ica_Subtract_Power_ico_mine_normori_eq_50_550_100ms_sx_ms5theta' \

##semolc evoked 
#'ClusPer_abs_sw_icomorphed_clusterp045_p05_17subj_SemLoc_ica_ConcreteAbstract_tail0_maxstep5' \

##typlex evoked
#'ClusPer_abs_sw_morphedico_cp05_p00985609756098_17subj_typlex_ica_WordPW_50_550_100ms_tail0_maxstep5' \

##typlex connectivity
#'ClusPer_stepw_Morphed_ico_TL_ica_equal_Sub_bestV_ctf_MI_Alpha_150_450_200ms_ms1_sx_002_05_lhMTL' \
#'ClusPer_stepw_Morphed_ico_TL_ica_equal_Sub_bestV_ctf_MI_Beta_150_450_200ms_ms1_sx_01_05_lhATL' \
#'ClusPer_stepw_Morphed_ico_TL_ica_equal_Sub_bestV_ctf_MI_Gamma_150_450_200ms_ms1_sx_001_05_lhATL' \
#'ClusP_sw_Morphed_ico_TL_ica_eq_sub_Mlttap_bestV_ctf_WPLI2d_Gamma_150_450_200ms_sx_ms1_005_05_MTLl' \
#'ClusP_sw_Morphed_ico_TL_ica_eq_sub_Mlttap_bestV_ctf_WPLI2d_Theta_150_450_200ms_sx_ms1_001_05_SMGl' \

##semloc connectivity
#'ClusP_sw_Morphed_ico_SL_ica_eq_Sub_Mlttap_bestV_ctf_Coherence_Alpha_150_450_200ms_ms1_005_05_ATLl' \
#'ClusP_sw_Morphed_ico_SL_ica_eq_Sub_Mlttap_bestV_ctf_WPLI2d_Gamma_150_450_200ms_ms1_005_05_MTLl' \
#'ClusP_sw_Morphed_ico_SL_ica_eq_Sub_Mlttap_bestV_ctf_WPLI2d_Gamma_150_450_200ms_ms1_005_05_pIFGl' \
#'ClusP_sw_Morphed_ico_SL_ica_eq_Sub_Mlttap_bestV_ctf_WPLI2d_Gamma_150_450_200ms_ms1_005_05_SMGl' \
#'ClusP_sw_Morphed_ico_SL_ica_equal_Sub_bestV_ctf_MI_Beta_150_450_200ms_ms1_sx_002_05_lhATL' \
#'ClusP_sw_Morphed_ico_SL_ica_equal_Sub_bestV_ctf_MI_Beta_150_450_200ms_ms1_sx_05_05_lhMTL' \
#'ClusP_sw_Morphed_ico_SL_ica_equal_Sub_bestV_ctf_MI_Gamma_150_450_200ms_ms1_sx_05_05_lhpIFG' \
#'ClusP_sw_Morphed_ico_SL_ica_equal_Sub_bestV_ctf_ST_Beta_150_450_200ms_ms1_sx_05_05_lhATL' \

###UVttest
##semloc evoked
#'UVttest_firstMorphed_ico_SemLoc_ica_Sub_Source_Evoked_mnrsmpl_50_550_100ms_0ov' \

##typlex evoked
#'UVttest_firstMorphed_ico_TL_ica_Sub_Source_Evoked_mrsmpl_50_550_100ms_0ov' \

##typlex power
#'UVttest_mineMorphed_ico_TL_ica_Sub_Power_normori_ratio_equal_mrsmpl_50_550_100ms_0ov_200hz_alpha' \
#'UVttest_mineMorphed_ico_TL_ica_Sub_Power_normori_ratio_equal_mrsmpl_50_550_100ms_0ov_200hz_beta' \
#'UVttest_mineMorphed_ico_TL_ica_Sub_Power_normori_ratio_equal_mrsmpl_50_550_100ms_0ov_200hz_theta' \

##semloc power
#'UVttest_mineMorphed_ico_SemLoc_ica_Subtract_Power2_normori_ratio_equalized_50_550_100ms_0ov_200hz_theta' \
#'UVttest_Morphed_ico_SL_ica_equal_Sub_Mlttap_bestV_ctf_ST_Beta_150_450_200ms_lhATL' \

##typlex power
'ClusPer_abs_sw_icomorphed_clusterp1_p05_19subj_SemDec_pnt1_30ica_Visual_Pwordc_maxstep1' \
'ClusPer_abs_sw_icomorphed_clusterp05_p05_19subj_SemDec_pnt1_30ica_Hear_Pwordc_maxstep1' \
'ClusPer_abs_sw_icomorphed_clusterp05_p05_19subj_SemDec_pnt1_30ica_Hand_Pwordc_maxstep1' \

)

nconds=${#conds[*]}
lastcond=`expr $nconds - 1`

for cc in `seq 0 ${lastcond}`
do
  echo " Condition  ${cc}" 

  mne_make_movie \
    --subject fsaverage \
    --smooth 5 \
    --stcin ${inpath}/${conds[cc]} \
    --scaleby 10000000000 \
    --tmin 50 \
    --tmax 450 \
    --tstep 16.666666 \
    --pickrange \
    --alpha 1.0 \
    --width 600 \
    --height 400 \
    --noscalebar \
    --nocomments \
    --view  lat \
    --mov ${outpath}/${conds[cc]} \
    --fthresh 0e10  --fmid 0.01e10 --fmax 0.02e10
done    

