# -*- coding: utf-8 -*-
"""
Created on Sat Jul  4 03:59:14 2015

@author: rf02
"""

[u'anterior_temporal-lh', u'anterior_temporal-rh', u'anterior_inferiorfrontal-lh', u'anterior_inferiorfrontal-rh', u'anterior_superiorfrontal-lh', u'anterior_superiorfrontal-rh', u'caudalmiddlefrontal-lh', u'caudalmiddlefrontal-rh', u'inferior_postcentral-lh', u'inferior_postcentral-rh', u'inferior_precentral-lh', u'inferior_precentral-rh', u'inferiorparietal-lh', u'inferiorparietal-rh', u'inferiortemporal-lh', u'inferiortemporal-rh', u'lateraloccipital-lh', u'lateraloccipital-rh', u'middle_postcentral-lh', u'middle_postcentral-rh', u'middle_precentral-lh', u'middle_precentral-rh', u'middle_superiorfrontal-lh', u'middle_superiorfrontal-rh', u'middle_temporal-lh', u'middle_temporal-rh', u'paracentral-lh', u'paracentral-rh', u'posterior_fusiform-lh', u'posterior_fusiform-rh', u'posterior_inferiorfrontal-lh', u'posterior_inferiorfrontal-rh', u'posterior_superiorfrontal-lh', u'posterior_superiorfrontal-rh', u'rostralmiddlefrontal-lh', u'rostralmiddlefrontal-rh', u'superior_postcentral-lh', u'superior_postcentral-rh', u'superior_precentral-lh', u'superior_precentral-rh', u'superior_temporal-lh', u'superior_temporal-rh', u'superiorparietal-lh', u'superiorparietal-rh', u'supramarginal-lh', u'supramarginal-rh']

l_new=[u'ATL', u'ATL', u'aIFG', u'aIFG', u'aSFG', u'aSFG', u'CMF', u'CMF', u'iPosC', u'iPosC', u'iPreC', u'iPreC', u'IPL', u'IPL', u'ITL', u'ITL', u'LOcci', u'LOcci', u'mPosC', u'mPosC', u'mPreC', u'mPreC', u'mSFG', u'mSFG', u'MTL', u'MTL', u'ParaC', u'ParaC', u'pFusi', u'pFusi', u'pIFG', u'pIFG',u'pSFG', u'pSFG', u'RMF', u'RMF', u'SPosC', u'SPosC', u'SPreC', u'SPreC',  u'STL', u'STL',u'SPL', u'SPL', u'SMarg', u'SMarg']

label_names=[u'ATL', u'ATL', u'aFusi', u'aFusi', u'aIFG', u'aIFG', u'aSFG', u'aSFG', u'CAC', u'CAC', u'CMF', u'CMF', u'cuneus', u'cuneus', u'entorhinal', u'entorhinal', u'Fpole', u'Fpole', u'iPosC', u'iPosC', u'iPreC', u'iPreC', u'IPL', u'IPL', u'ITL', u'ITL', u'insula', u'insula', u'isthmuscingulate', u'isthmuscingulate', u'LOcci', u'LOcci', u'lingual', u'lingual', u'MedOrbiF', u'MedOrbiF', u'mSFG', u'mSFG', u'MTL', u'MTL', u'ParaC', u'ParaC', u'ParaHipCamp', u'ParaHipCamp', u'Pericalcarine', u'Pericalcarine', u'pFusi', u'pFusi', u'pIFG', u'pIFG', u'pSFG', u'pSFG', u'PosCing', u'PosCing', u'Precuneus-lh', u'Precuneus-rh', u'RosAntCing', u'RosAntCing', u'RMF', u'RMF', u'sPosC', u'sPosC', u'sPreC', u'sPreC', u'STL', u'STL', u'SPL', u'SPL', u'SMG', u'SMG']